"""S0 — Action / Ack / JudgeManifest / Approval / DLQEntry / SideEffect (design §4.5).

These are the remaining §4.5 contracts. Notably:

* :class:`Ack` is the **AckInbox** completion signal a worker/audit/fixer drops —
  it is NOT an :class:`~handoff_fanout.supervisor.events.Event` (different writer).
  The supervisor reads the AckInbox and appends the corresponding event itself,
  preserving the single-writer invariant (INV-3 / design §4.2 C2b).
* :class:`Approval` is generated by the dumb CLI (C18), never hand-written
  (INV-10), and is bound to an exact hash with a hard expiry (anti-replay, no
  infinite approval).
* :class:`DLQEntry` is human-facing (INV-10): a non-technical owner must be able
  to read the reason / options / worst-case and act.

This module has no dependency on plan/fixer (they depend on :class:`SideEffect`
here), keeping the import graph acyclic.
"""

from __future__ import annotations

import dataclasses
import enum

from ._base import Contract, SchemaError
from .events import Provenance


class SideEffectKind(enum.StrEnum):
    """Categories of side effect the SideEffectRegistry tracks for rollback
    (design §4.5 / §10 — migration / artefact / approval / external account)."""

    DB_MIGRATION = "db_migration"
    ARTIFACT = "artifact"
    APPROVAL = "approval"
    EXTERNAL_ACCOUNT = "external_account"
    FILESYSTEM = "filesystem"
    NETWORK = "network"


@dataclasses.dataclass
class SideEffect(Contract):
    """A non-pure effect a node may produce (design §4.5).

    ``compensation`` is how to undo it; ``needs_preauth`` flags an irreversible
    effect that may not run without an :class:`Approval`. S0-fix P1-7 makes INV-6
    a *schema-shape* fact: a SideEffect that is **neither sandboxed nor dry-run,
    has no compensation, and does not require pre-auth** is an *unauthorized
    irreversible* effect — it is rejected at construction (fail-closed), so the
    shape can never even express "do an irreversible thing with no way back and no
    approval".
    """

    kind: SideEffectKind
    sandboxed: bool = True
    dry_run: bool = False
    compensation: str | None = None
    needs_preauth: bool = False

    def validate(self) -> None:
        # INV-6: irreversible ⇒ compensable OR pre-authorized. A real (not
        # sandboxed, not dry-run) effect with no compensation AND no pre-auth gate
        # is exactly the unauthorized-irreversible combo the design forbids.
        if (
            not self.sandboxed
            and not self.dry_run
            and self.compensation is None
            and not self.needs_preauth
        ):
            raise SchemaError(
                "SideEffect is unauthorized-irreversible (INV-6): a non-sandboxed, "
                "non-dry-run effect must have a `compensation` or set "
                "`needs_preauth=True`"
            )


@dataclasses.dataclass
class Action(Contract):
    """A planned, idempotent, fenced effecting action (design §4.5).

    ``idempotency_key`` makes a re-dispatch a no-op; ``fencing_token`` lets a
    stale/revived attempt be rejected (INV-4 at-least-once + fencing).
    """

    action_id: str
    idempotency_key: str
    input_hash: str
    fencing_token: str
    preconditions: list[str] = dataclasses.field(default_factory=list)
    effects: list[SideEffect] = dataclasses.field(default_factory=list)

    def validate(self) -> None:
        if not self.action_id:
            raise SchemaError("Action.action_id required")
        if not self.idempotency_key:
            raise SchemaError("Action.idempotency_key required (INV-4 idempotency)")
        if not self.input_hash:
            raise SchemaError("Action.input_hash required (INV-4 idempotency binding)")
        if not self.fencing_token:
            raise SchemaError("Action.fencing_token required (INV-4 fencing)")


@dataclasses.dataclass
class Ack(Contract):
    """AckInbox completion signal (design §4.5 / §4.2 C2b).

    Written by a worker/audit/fixer, NOT the supervisor. Carries the binding
    hashes (``tree_oid`` / ``staged_diff_hash``) the supervisor needs to bind the
    audit + verdict to the exact code state.
    """

    node: str
    run_id: str
    attempt: int
    commit: str | None = None
    tree_oid: str | None = None
    staged_diff_hash: str | None = None
    tests_ran: list[str] = dataclasses.field(default_factory=list)

    def validate(self) -> None:
        if not self.node:
            raise SchemaError("Ack.node required")
        if not self.run_id:
            raise SchemaError("Ack.run_id required")
        if self.attempt < 1:
            raise SchemaError("Ack.attempt must be >= 1")
        # The supervisor binds the audit + verdict to the exact code state the
        # worker produced (design §6.1), so an Ack must carry at least one binding
        # hash — otherwise the verdict has nothing to bind to (R2 codex C-P1-9).
        if not self.tree_oid and not self.staged_diff_hash:
            raise SchemaError(
                "Ack must carry at least one of `tree_oid` / `staged_diff_hash` "
                "(INV-4 anti-replay binding)"
            )


@dataclasses.dataclass
class JudgeManifestEntry(Contract):
    """One write-protected judge artefact (oracle/test/check script) + its hash
    (design §4.5 ``JudgeManifest{path,hash}[]`` / INV-5 soft write protection)."""

    path: str
    hash: str

    def validate(self) -> None:
        if not self.path:
            raise SchemaError("JudgeManifestEntry.path required")
        if not self.hash:
            raise SchemaError("JudgeManifestEntry.hash required")


@dataclasses.dataclass
class JudgeManifest(Contract):
    """The full set of write-protected judge artefacts, hashed before a run so a
    worker tampering with a judge fails closed (INV-5; honest: soft, see §7)."""

    entries: list[JudgeManifestEntry] = dataclasses.field(default_factory=list)

    def validate(self) -> None:
        paths = [e.path for e in self.entries]
        dupes = sorted({p for p in paths if paths.count(p) > 1})
        if dupes:
            raise SchemaError(f"JudgeManifest has duplicate paths: {dupes}")


@dataclasses.dataclass
class Approval(Contract):
    """Owner approval for an irreversible step (design §4.5 / §6.4 / INV-10).

    Generated by C18 (handoff-cli), never hand-written. Bound to an exact hash
    with a hard ``expires_at`` so one approval can never be silently replayed onto
    a different change or used forever.
    """

    node: str
    grantor: str
    granted_at: str
    expires_at: str
    bound_hash: str
    conditions: list[str] = dataclasses.field(default_factory=list)

    def validate(self) -> None:
        if not self.node:
            raise SchemaError("Approval.node required")
        if not self.grantor:
            raise SchemaError("Approval.grantor required")
        if not self.granted_at:
            raise SchemaError("Approval.granted_at required")
        if not self.expires_at:
            raise SchemaError("Approval.expires_at required (no infinite approval)")
        if not self.bound_hash:
            raise SchemaError("Approval.bound_hash required (INV-4 anti-replay)")


@dataclasses.dataclass
class DLQEntry(Contract):
    """Dead-letter entry — a node that exhausted its budget/attempts and needs a
    human (design §4.5 / §11 / INV-10). Every field is human-facing: a
    non-technical owner reads ``reason`` / ``options`` / ``worst_case`` and picks.
    """

    node: str
    reason: str
    impact: str
    recommended: str
    worst_case: str
    options: list[str] = dataclasses.field(default_factory=list)
    #: S0-fix P2-9: a typed :class:`Provenance` (was a bare untyped ``dict``), so
    #: the DLQ entry's binding is recursively schema-validated, not free-form.
    provenance: Provenance | None = None

    def validate(self) -> None:
        if not self.node:
            raise SchemaError("DLQEntry.node required")
        if not self.reason:
            raise SchemaError("DLQEntry.reason required")
        if not self.options:
            raise SchemaError("DLQEntry.options required (owner needs choices, INV-10)")
        if not self.recommended:
            raise SchemaError("DLQEntry.recommended required (INV-10)")
